In [58]:
import pandas as pd

In [59]:
df = pd.read_csv("OECD.TAD.ARPDSD_AGRI_ENVDF_AEI1.0-.A......csv")
df.head()

,STRUCTURE,STRUCTURE_ID,STRUCTURE_NAME,ACTION,REF_AREA,Reference area,FREQ,Frequency of observation,MEASURE,Measure,...,OBS_VALUE,Observation value,DECIMALS,Decimals,OBS_STATUS,Observation status,UNIT_MULT,Unit multiplier,BASE_PER,Base period
0,DATAFLOW,OECD.TAD.ARP:DSD_AGRI_ENV@DF_AEI(1.0),Agri-environmental indicators: all data,I,AUT,Austria,A,Annual,BRN,Nutrient removal by crop residues burned on th...,...,0.0,NaN,2,Two,A,Normal value,0,Units,NaN,NaN
1,DATAFLOW,OECD.TAD.ARP:DSD_AGRI_ENV@DF_AEI(1.0),Agri-environmental indicators: all data,I,AUT,Austria,A,Annual,BRN,Nutrient removal by crop residues burned on th...,...,0.0,NaN,2,Two,A,Normal value,0,Units,NaN,NaN
2,DATAFLOW,OECD.TAD.ARP:DSD_AGRI_ENV@DF_AEI(1.0),Agri-environmental indicators: all data,I,AUT,Austria,A,Annual,BRN,Nutrient removal by crop residues burned on th...,...,0.0,NaN,2,Two,A,Normal value,0,Units,NaN,NaN
3,DATAFLOW,OECD.TAD.ARP:DSD_AGRI_ENV@DF_AEI(1.0),Agri-environmental indicators: all data,I,AUT,Austria,A,Annual,BRN,Nutrient removal by crop residues burned on th...,...,0.0,NaN,2,Two,A,Normal value,0,Units,NaN,NaN
4,DATAFLOW,OECD.TAD.ARP:DSD_AGRI_ENV@DF_AEI(1.0),Agri-environmental indicators: all data,I,AUT,Austria,A,Annual,BRN,Nutrient removal by crop residues burned on th...,...,0.0,NaN,2,Two,A,Normal value,0,Units,NaN,NaN

In [60]:
df = df.drop(columns=['STRUCTURE', 'STRUCTURE_ID', 'STRUCTURE_NAME', 'ACTION', 'Observation value', 'Decimals', 'Base period', 'FREQ', 'Frequency of observation', 'Time period', 'DECIMALS', 'BASE_PER'])

In [61]:
df.head()

,REF_AREA,Reference area,MEASURE,Measure,EROSION_LEVEL,Erosion risk level,WATER_TYPE,Water type,NUTRIENTS,Nutrients,UNIT_MEASURE,Unit of measure,TIME_PERIOD,OBS_VALUE,OBS_STATUS,Observation status,UNIT_MULT,Unit multiplier
0,AUT,Austria,BRN,Nutrient removal by crop residues burned on th...,_Z,Not applicable,_Z,Not applicable,PHOSPHORUS,Phosphorus,T,Tonnes,2012,0.0,A,Normal value,0,Units
1,AUT,Austria,BRN,Nutrient removal by crop residues burned on th...,_Z,Not applicable,_Z,Not applicable,PHOSPHORUS,Phosphorus,T,Tonnes,2013,0.0,A,Normal value,0,Units
2,AUT,Austria,BRN,Nutrient removal by crop residues burned on th...,_Z,Not applicable,_Z,Not applicable,PHOSPHORUS,Phosphorus,T,Tonnes,2014,0.0,A,Normal value,0,Units
3,AUT,Austria,BRN,Nutrient removal by crop residues burned on th...,_Z,Not applicable,_Z,Not applicable,PHOSPHORUS,Phosphorus,T,Tonnes,2015,0.0,A,Normal value,0,Units
4,AUT,Austria,BRN,Nutrient removal by crop residues burned on th...,_Z,Not applicable,_Z,Not applicable,PHOSPHORUS,Phosphorus,T,Tonnes,2016,0.0,A,Normal value,0,Units

In [62]:
for i in df.columns:
    print(i, df[i].unique())

REF_AREA ['AUT' 'CZE' 'FIN' 'FRA' 'HUN' 'IRL' 'NLD' 'NOR' 'POL' 'PRT' 'SVK' 'SVN'
 'SWE' 'GBR' 'HRV' 'ROU' 'ITA' 'LVA' 'BGR' 'ESP' 'CAN' 'COL' 'EST' 'LTU'
 'ISL' 'EU28' 'MLT' 'DNK' 'GRC' 'LUX' 'CYP' 'BEL' 'DEU' 'CHE' 'AUS' 'CHL'
 'ISR' 'JPN' 'KOR' 'MEX' 'TUR' 'USA' 'ARG' 'CRI' 'BRA' 'CHN' 'IND' 'IDN'
 'KAZ' 'RUS' 'ZAF' 'UKR' 'VNM' 'EU27' 'NZL' 'EU' 'EU27_2020' 'PHL' 'PER'
 'BE2' 'BE3']
Reference area ['Austria' 'Czechia' 'Finland' 'France' 'Hungary' 'Ireland' 'Netherlands'
 'Norway' 'Poland' 'Portugal' 'Slovak Republic' 'Slovenia' 'Sweden'
 'United Kingdom' 'Croatia' 'Romania' 'Italy' 'Latvia' 'Bulgaria' 'Spain'
 'Canada' 'Colombia' 'Estonia' 'Lithuania' 'Iceland'
 'European Union (28 countries)' 'Malta' 'Denmark' 'Greece' 'Luxembourg'
 'Cyprus' 'Belgium' 'Germany' 'Switzerland' 'Australia' 'Chile' 'Israel'
 'Japan' 'Korea' 'Mexico' 'TÃ¼rkiye' 'United States' 'Argentina'
 'Costa Rica' 'Brazil' 'China (Peopleâ€™s Republic of)' 'India' 'Indonesia'
 'Kazakhstan' 'Russia' 'South Africa' 'Ukraine' 'Viet Nam'
 'European Union (27 countries)' 'New Zealand' 'European Union'
 'European Union (27 countries from 01/02/2020)' 'Philippines' 'Peru'
 'Flemish Region' 'Wallonia']
MEASURE ['BRN' 'M23' 'M21' 'F12' 'RES' 'M_PEST' 'OT_PEST' 'C222' 'NH3AGR' 'C000'
 'A19' 'C221' 'A14' 'C22' 'C217' 'B1' 'C211' 'C213' 'OO' 'A11' 'C1' 'B0'
 'F11' 'A13' 'O1' 'I0' 'M1' 'A12' 'C21' 'A1' 'F1' 'L111' 'I_PEST' 'F_PEST'
 'H_PEST' 'TOTPEST' 'NH3TOT' 'C212' 'TR' 'RICE' 'MANURE' 'CO2AGR' 'GHG_AG'
 'HFC' 'CH4_LULUCF' 'SETT_CO2' 'CL_CH4' 'IPP' 'FB_AR2' 'CH4AGR' 'AGR_SOIL'
 'CL_CO2' 'EI' 'N2O' 'FB_AR' 'UA' 'AGR' 'OTH_SECTOR' 'CO2_LULUCF'
 'TOTGHG_LULUCF' 'LIM' 'OT_N2O' 'N2OAGR' 'TOTGHG_SOURCE' 'GL_N2O'
 'TOTGHG_LULU' 'GL_CO2' 'MIC' 'PFC' 'EF' 'GL_CH4' 'F_N2O' 'WET_N2O'
 'HWP_CO2' 'F_CH4' 'F_CO2' 'SETT_N2O' 'SETT_CH4' 'WASTE' 'TOTGHG_GAZ'
 'CL_N2O' 'SF' 'NRJ' 'N2O_LULUCF' 'CO2' 'CH4' 'WET_CH4' 'OTHER_CO2'
 'OTH_CARB' 'OTHER_N2O' 'OT_CO2' 'OTHER_CH4' 'OT_CH4' 'OTH_CH4' 'OTH_N2O'
 'OTH' 'OTH_CO2' 'WET_CO2' 'MANUR' 'PB_S' 'PB_S2' 'PERMA' 'IRRIGABLEAREA'
 'IRRIGATIONAREA' 'PERMPASTURE' 'T_CROP' 'O_F' 'A_LAND' 'A_P_CROP'
 'TOTAGR_LAND' 'B0_H' 'TOTNRJAG' 'TOTNRJ' 'BIRDS' 'BIRDSF' 'AGN' 'AGP'
 'MONITSITEP' 'AGPEST' 'MONITSITEPEST' 'MONITSITESN' 'TOTFRESHAG'
 'TOTFRESHW' 'WIND_SOIL' 'WATER_SOIL']
Measure ['Nutrient removal by crop residues burned on the field' 'Manure imports'
 'Manure withdrawals' 'Organic fertilisers (excluding livestock manure)'
 'Nutrient removal by crop residues removed from the field'
 'Total molluscicides' 'Sales of other pesticides' 'Pasture'
 'Agricultural ammonia (NH3)' 'Other crops' 'Other livestock'
 'Harvested fodder crops' 'Poultry' 'Forage' 'Industrial crops'
 'Biological fixation' 'Cereals' 'Dried pulses and beans'
 'Nutrient outputs' 'Cattle' 'Seeds and planting materials'
 'Balance (inputs minus outputs)' 'Inorganic fertilisers'
 'Sheep and goats' 'Other nutrient inputs' 'Nutrient inputs'
 'Net input of manure' 'Pigs' 'Harvested crops'
 'Livestock manure production' 'Fertilisers' 'Atmospheric deposition'
 'Sales of insecticides' 'Sales of fungicides' 'Sales of herbicides'
 'Total sales of agricultural pesticides' 'Ammonia (NH3)' 'Oil crops'
 'Transport' 'Rice cultivation' 'Manure management'
 'Total Carbone dioxide (CO2) from agriculture'
 'Total greenhouse gas emissions from agriculture'
 'Hydrofluorocarbons (HFCs)' 'Total methane (CH4)' 'Settlements'
 'Cropland' 'Industrial processes and product use'
 'Field burning of agricultural residues'
 'Total methane (CH4) from agriculture' 'Agricultural soil'
 'Energy industries' 'Nitrous oxide (N2O)' 'Urea application'
 'Agriculture' 'Other sectors' 'Total Carbone dioxide (CO2)'
 'Total greenhouse gas from LULUCF' 'Liming' 'Others'
 'Total nitrous oxide (N2O) from agriculture'
 'Total greenhouse gas emissions by source (without LULUCF)' 'Grassland'
 'Total greenhouse gas emissions with LULUCF'
 'Manufacturing industries and construction' 'Perfluorocarbons (PFCs)'
 'Enteric fermentation' 'Forest land' 'Wetlands' 'Harvest wood products'
 'Waste' 'Total greenhouse gas emissions by gas (without LULUCF)'
 'Sulphur hexafluoride (SF6)' 'Energy' 'Total Nitrous oxide (N2O)'
 'Carbon dioxide (CO2)' 'Methane (CH4)' 'Other land'
 'Other carbon-containing fertilisers' 'Others CH4' 'Others N2O' 'Other'
 'Others CO2' 'Prescribed burning of savannas' 'Permanent crops'
 'Irrigable area' 'Irrigation area' 'Permanent pasture' 'Transgenic crops'
 'Organic farming' 'Arable land' 'Arable and permanent crop land'
 'Total agricultural land area' 'Balance per hectare'
 'Direct on-farm energy consumption' 'Total final energy consumption'
 'Farmland birds index' 'Forest birds index'
 'Share of agriculture in total emissions of nitrate'
 'Share of agriculture in total emissions of phosphate'
 'Share of monitoring sites in agricultural areas that exceed recommended drinking water limits for phosphorus'
 'Share of monitoring sites in agricultural areas where one or more pesticides are present'
 'Share of monitoring sites in agricultural areas that exceed recommended drinking water limits for pesticides'
 'Share of monitoring sites in agricultural areas that exceed recommended drinking water limits for nitrate'
 'Agriculture freshwater abstraction' 'Total freshwater abstraction'
 'Wind erosion' 'Water erosion']
EROSION_LEVEL ['_Z' 'MD' 'LW' 'HG' '_T' 'TOL' 'SV']
Erosion risk level ['Not applicable' 'Moderate' 'Low' 'High' 'Total' 'Tolerable' 'Severe']
WATER_TYPE ['_Z' 'SW' 'CW' 'GW' '_T']
Water type ['Not applicable' 'Surface water' 'Coastal water' 'Ground water' 'Total']
NUTRIENTS ['PHOSPHORUS' 'NITROGEN' '_Z']
Nutrients ['Phosphorus' 'Nitrogen' 'Not applicable']
UNIT_MEASURE ['T' 'T_CO2E' 'HA' 'KG' 'TOE' 'IX' 'PT_EM_NO3' 'PT_EM_PO4' 'PT_MNTR_STS'
 'M3' 'PT_ALAR']
Unit of measure ['Tonnes' 'Tonnes of CO2-equivalent' 'Hectares' 'Kilogramme'
 'Tonnes of oil equivalent' 'Index' 'Percentage of nitrate emissions'
 'Percentage of phosphate emissions' 'Percentage of monitoring sites'
 'Cubic metres' 'Percentage of agricultural land area']
TIME_PERIOD [2012 2013 2014 2015 2016 2017 2018 2019 2020 2021 2022 2023]
OBS_VALUE [   0.      57.    2137.    ...   11.709    6.165    6.33 ]
OBS_STATUS ['A' 'E' 'B']
Observation status ['Normal value' 'Estimated value' 'Time series break']
UNIT_MULT [0 3 6]
Unit multiplier ['Units' 'Thousands' 'Millions']

In [63]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53592 entries, 0 to 53591
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   REF_AREA            53592 non-null  object
 1   Reference area      53592 non-null  object
 2   MEASURE             53592 non-null  object
 3   Measure             53592 non-null  object
 4   EROSION_LEVEL       53592 non-null  object
 5   Erosion risk level  53592 non-null  object
 6   WATER_TYPE          53592 non-null  object
 7   Water type          53592 non-null  object
 8   NUTRIENTS           53592 non-null  object
 9   Nutrients           53592 non-null  object
 10  UNIT_MEASURE        53592 non-null  object
 11  Unit of measure     53592 non-null  object
 12  TIME_PERIOD         53592 non-null  int64
 13  OBS_VALUE           53592 non-null  float64
 14  OBS_STATUS          53592 non-null  object
 15  Observation status  53592 non-null  object
 16  UNIT_MULT           53592 non-null  int64
 17  Unit multiplier     53592 non-null  object
dtypes: float64(1), int64(2), object(15)
memory usage: 7.4+ MB

In [64]:
df.isnull().any()

REF_AREA              False
Reference area        False
MEASURE               False
Measure               False
EROSION_LEVEL         False
Erosion risk level    False
WATER_TYPE            False
Water type            False
NUTRIENTS             False
Nutrients             False
UNIT_MEASURE          False
Unit of measure       False
TIME_PERIOD           False
OBS_VALUE             False
OBS_STATUS            False
Observation status    False
UNIT_MULT             False
Unit multiplier       False
dtype: bool

In [69]:
df.isna().any()

REF_AREA              False
Reference area        False
MEASURE               False
Measure               False
EROSION_LEVEL         False
Erosion risk level    False
WATER_TYPE            False
Water type            False
NUTRIENTS             False
Nutrients             False
UNIT_MEASURE          False
Unit of measure       False
TIME_PERIOD           False
OBS_VALUE             False
OBS_STATUS            False
Observation status    False
UNIT_MULT             False
Unit multiplier       False
dtype: bool